# Generated by Django 3.0.4 on 2020-03-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='geeks_field',
        ),
    ]
