# Generated by Django 3.0.4 on 2020-04-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200407_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_mail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='c_psw',
            field=models.CharField(default='hii@123', max_length=20),
        ),
    ]
